desc "Load Linda's tags and links for usability testing"
task linda_tags_and_links: :environment do
  # Set this based on the db ID of Lindas recording at the time
  recording = Recording.find(9)

  @utterances.each_with_index do |u, i|
    # Crete the Utterance record
    utterance_record = Utterance.create!(
      index: i + 1,
      text: u[0],
      begins_at: u[1],
      ends_at: u[2],
      recording: recording
    )

    # Create tags if any
    @tags.select{|t| t[0] == i}.each do |t|
      Tag.create!(
        utterance: utterance_record,
        tag_type: TagType.find(t[1])
      )
    end
    
    # Create links if any
    @links.select{|l| l[2] == i}.each do |l|
      Link.create!(
        label: l[0],
        url: l[1],
        utterance: utterance_record
      )
    end
  end
end

# utterance_index, tag_type_id
@tags = [
  [7,2], [37,2], [75,3], [8,2], [10,2], [11,2], [37,3], [42,2], [47,3], [49,3], [51,2], [55,2],
  [67,1], [75,1], [104,3], [115,1], [117,3]
]

# label, url, utterance index
@links = [
  ['Norco', 'https://medlineplus.gov/druginfo/meds/a601006.html', 7 ],
  ['Gabapentin', 'https://medlineplus.gov/druginfo/meds/a694007.html', 7 ],
  ['Tramadol', 'https://medlineplus.gov/druginfo/meds/a695011.html', 7 ],
  ['high blood pressure', 'https://medlineplus.gov/highbloodpressure.html', 14 ],
  ['Gabapentin', 'https://medlineplus.gov/druginfo/meds/a694007.html', 37 ],
  ['shingles', 'https://medlineplus.gov/shingles.html', 37 ],
  ['Gabapentin', 'https://medlineplus.gov/druginfo/meds/a694007.html', 42 ],
  ['Gabapentin', 'https://medlineplus.gov/druginfo/meds/a694007.html', 47 ],
  ['Gabapentin', 'https://medlineplus.gov/druginfo/meds/a694007.html', 51 ],
  ['foot pain', 'https://medlineplus.gov/ency/article/003183.htm', 55 ],
  ['bunion', 'https://medlineplus.gov/ency/article/001231.htm', 55 ],
  ['arthritis', 'https://medlineplus.gov/arthritis.html', 55 ],
  ['arthritis', 'https://medlineplus.gov/arthritis.html', 67 ],
  ['ganglion cyst', 'https://www.assh.org/handcare/hand-arm-conditions/ganglion-cyst', 75 ],
  ['ganglion cyst', 'https://www.assh.org/handcare/hand-arm-conditions/ganglion-cyst', 102 ],
  ['ganglion cyst', 'https://www.assh.org/handcare/hand-arm-conditions/ganglion-cyst', 115 ],
  ['blood count test', 'https://medlineplus.gov/bloodcounttests.html', 131 ],
  ['pain management', 'http://www.asahq.org/whensecondscount/pain-management/', 145 ],
  ['pain management', 'http://www.asahq.org/whensecondscount/pain-management/', 149 ],
  [ 'blood pressure measurement', 'https://medlineplus.gov/ency/article/007490.htm', 195, ]
]

# text, start_time, end_time],
@utterances = [
  ["How are you feeling overall?",0,2],
  ["Well, you notice when I do this -",2,3],
  ["Um-hum.",3,4],
  ["- in my foot.",4,5],
  ["Um-hum.",5,6],
  ["Then my both legs now.",6,8],
  ["Yeah.",8,9],
  ["But the pain, I can control in the back, you know, with the Norco, and ah, what is that other stuff that you gave me?",9,14],
  ["Gabapentin maybe?",14,16],
  ["No, no, no.",16,17],
  ["Or the Tramadol?",17,18],
  ["Yeah. Those 2 helped with the pain that I have from the surgery on my back but they don't help nerve.",18,22],
  ["Right.  Well, they can to a point but not -",22,25],
  ["I don't feel well on some days.",25,27],
  ["And your blood pressure is pretty high today as well.",27,30],
  ["Yeah, I know.  I wasn't feeling good today, so _____ I just ran into the shower and got down here.",30,36],
  ["Have you - At one point, we were checking blood pressure fairly irregularly, have you checked it on the past -",36,42],
  ["I haven't.",42,43],
  ["Month or so?",43,44],
  ["No.",44,45],
  ["So, just _____ if you could maybe just check it once or twice sometime.",45,49],
  ["Okay.",49,50],
  ["Between now and the end of the month.  And if it is up for some reason, then give us a call.",50,54],
  ["Okay.",54,56],
  ["So, you check blood pressure at home a few times and call if - because we kinda had the same thing before where you come in here, it's pretty high and then you checked it at home, and we checked your machine and it was pretty good.  So, whatever numbers you get will be -",56,72],
  ["Yeah, its, its, I know, -",72,74],
  ["Not just today.",74,75],
  ["- I'll be high today.",75,76],
  ["Yeah.",76,77],
  ["Yeah, because I was trying to handle a lot of things this morning.",77,80],
  ["Sleep-wise, how have you been doing these days?",80,82],
  ["Well, I was doing very good until this hour change, My God.",82,86],
  ["Okay, well then, we were to, just the rest _____ .",86,89],
  ["I mean, it never bothered me before when they do that.  Then all of the sudden, I don't know _____ what day it is.",89,95],
  ["That's okay.  You don't need to be asked.",95,98],
  ["So, pain-wise, remember before -",98,100],
  ["It’s painful.",100,101],
  ["Yeah.  Before you were on the gabapentin that we had used for the shingles pain, remember when you had all that herpes shingles last year?  That is a nerve pain controller drug and that's what it was designed for.",101,112],
  ["What was this called?",112,114],
  ["The gabapentin, Neurontin.  It's not really strong but -",114,118],
  ["No.",118,120],
  ["- it is what it is.  Its kind of - it's probably the best one out there for this.",120,124],
  ["There is a reason, one of the reasons I quit gabapentin was because I put on weight.  I mean, immediately I start gaining and I have never liked it.  Its not",124,132],
  ["Ahhh, so -",132,133],
  ["And I don't try anything.",133,135],
  ["Yeah.  It was probably because you don't bruise much as you used to be -",135,139],
  ["That's true.",139,140],
  ["But isn't that about.  There's not really any that are going to be likely to make much of the difference.",140,147],
  ["Okay.",147,149],
  ["That wouldn't have - although, the gabapentin for most people who tend to be weight gainer, yeah, it's a very common rather to most people.",149,156],
  ["_____ like it didn't make no difference but it didn't affect this way.",156,160],
  ["Right, and mostly, I mean, there are so many people who had gabapentin.  I've got, I don't know how many patients, but more than I can count who use for this, but again.",160,170],
  ["Should I try it again?  I've got -",170,173],
  ["I would try it.  Do you remember what dosages those were?  I'll tell you what I had sent in before.",173,179],
  ["No, I don't.",179,180],
  ["Probably, 300 mg, be my guest, but I'll tell you.  300 mg and I had also sent in 100 mg, but the last one I sent in were 300.  When do you notice that the foot pain is the worst?",180,192],
  ["All the time.  It never, never ceases.  It wakes me up at night.",192,196],
  ["And still the right side is worst than the other one?",196,199],
  ["Yes, both from now but it's the right-sided toe is -",199,202],
  ["With the bunion?",202,203],
  ["Yeah.  That's the one that hurts the most.",203,205],
  ["So that's -",205,206],
  ["And then the arthritis is really starting to get _____ with the, with everything I had, I mean, my fingers are twisting, you -",206,214],
  ["Um-hum.",214,215],
  ["- and they hurt.  And, there's a pain right here that, I don't know what the heck it is but if it touches, that makes it real painful.",215,221],
  ["Um-hum.",221,222],
  ["Are they arthritis?",222,224],
  ["Well, some of that is arthritis, yeah.",224,226],
  ["But, you can feel the bone.",226,228],
  ["Yeah.  Arthritis, these are the classic basis of being arthritis ____ .",228,232],
  ["How's that?",232,234],
  ["Will be through here but you get more of it -",234,237],
  ["Right here.",237,238],
  ["You get more of it here is it?",238,240],
  ["No.  Right here.  Right, right here in this area",240,243],
  ["So, that's, that's a little ganglion cyst, it's on the tendon.  So, the reason my hand closes is because I've got muscles up here that contract, closes my finger this was way, right.  So, you can almost imagine a pulley.",243,256],
  ["Um-hum.",256,258],
  ["Right.  And the reason that those pulleys don't spring up is because there's a bunch of little straps all the way down and those straps can have their own body fluid that comes.",258,266],
  ["Good.",266,268],
  ["_____  Well, in that process of being able to do that -",268,270],
  ["Um-hum.",270,271],
  ["- you can get a little cyst in those -",271,273],
  ["Oh.",273,274],
  ["_____ that is 99% probable.",274,276],
  ["Right.",276,277],
  ["Both can be removed surgically.  So, we could have, like a surgeon do that if it bothers you too much.",277,282],
  ["Um-hum.",282,283],
  ["But you don't have to.",283,284],
  ["They don't mean anything.  The doctor _____.",284,287],
  ["I know.  It's a last resort but I'm just kinda letting you know that, some things that you could do as need be but -",287,294],
  ["Yeah.",294,295],
  ["So, if it's bothering you with the things that you'd like to do, like painting or just -",295,298],
  ["That's right.",298,299],
  ["- the stuff around the house.",299,300],
  ["Um-hum.",300,301],
  ["Then, just let me know.",301,302],
  ["Okay.",302,303],
  ["It's a pretty minor procedure.  Had you seen any of the ortho that is in town like Johnson or Smith before?  Ring any bells?",303,312],
  ["Who?",312,313],
  ["Dr. Johnson or Dr. Smith, the orthopedic surgeon.",313,316],
  ["Oh.  I think Dr. Smith once.",316,318],
  ["So, he does those in the office.",318,320],
  ["So, we could always have you go see him again and you guys can talk about that ganglion cyst.",320,325],
  ["Okay.",325,327],
  ["That's about an easiest procedure, that is in and out of the office like, like this.  Um, let me just put it on here I guess.  That's the right hand's, the middle finger?",327,337],
  ["Um-hum.",337,338],
  ["I know what you were doing when you were a youth.",338,340],
  ["Oh.",340,341],
  ["Using that finger too often.",341,343],
  ["Not really.",343,344],
  ["That's what they all say.  You have done lot, lots of stuff, played music, had kids -",344,350],
  ["I bet what's why I'm -",350,351],
  ["_____ make art.",351,352],
  ["- trying things, just a few if I can do it and then, I'll move on to something else.  So, -",352,357],
  ["That's a good thing to do.",357,359],
  ["So, that's a third right flexor.  Flexor, um, probable small ganglion cyst.",359,365],
  ["Like what is that?",365,367],
  ["No one really knows.  They, they predicted some type of the trauma whether it's like a bang to it or just a slow progression.",367,375],
  ["I noticed it last year, last, um, summer exactly.",375,379],
  ["Yeah.",379,380],
  ["_____ go away.",380,381],
  ["The catching you mean, or the bump or both.",381,383],
  ["It was when I was writer, you know.",383,385],
  ["Yeah.",385,386],
  ["And that's how it started.",386,387],
  ["Well, if it's really interfering with the things that you'd like to do, I'd go see him sooner.",387,392],
  ["Yeah.",392,393],
  ["You want me to send a referral out now or do you want, ah?",393,396],
  ["No.",396,397],
  ["Okay.  All you need to do is give us a call.",397,399],
  ["I will.",399,401],
  ["So, I will say, see ortho if symptoms worsen, how does that sound?",401,404],
  ["Okay.",404,406],
  ["When do we get blood work done last?",406,408],
  ["Well, like few months ago.",408,410],
  ["Like a few months?  Or not even?",410,413],
  ["I think that was in the fall, wasn't it?",413,415],
  ["Last spring.",415,416],
  ["I don't even remember.",416,417],
  ["Yeah.  So, we will need to get lab work done, unless you had it done in the past week or something?",417,422],
  ["No.",422,424],
  ["It's been a year.",424,425],
  ["Is that right?",425,426],
  ["Yeah. So, we're not too far behind but lets get a - we will check the thyroid as well.  So, we will get some annual labs -",426,433],
  ["Copy.",433,434],
  ["Um, we had talked about other options for overall pain control, one would be, you know, going to that pain clinic in Woodstock.",434,442],
  ["It's almost no for me.  I can't take off and go down there.",442,446],
  ["Well, here's what I would do?",446,448],
  ["You want me to drive that far.",448,450],
  ["Right.  It might be worth just going in and sitting down … they are pain specialists, so they know more about pain management than I do.  If they come up with the great plans and I can continue with that.",450,460],
  ["Okay.",460,462],
  ["So, I'd like their brain.",462,463],
  ["Um-hum.",463,464],
  ["If I could steal their brain, I would just use it, but it would be good for them to sit down with you and say, here's where you are.  This is probably a better long-term solution based on who you are, how old you are and what you can get from them.  And then, unless it is something really, … that I cannot do, then they'll probably be happy and after that to do it for you anyway _____-",464,485],
  ["PATIENT: What's his name?",485,486],
  ["Peterson?",486,487],
  ["Yeah, yeah.",487,488],
  ["Yeah.",488,489],
  ["Yeah.",488,489],
  ["Dr. Peterson is a good guy.",489,491],
  ["Okay.",491,492],
  ["We could have you see Peterson.  Just to kind of maybe have a one-time go over everything and then you could decide if you want him to manage it -",492,499],
  ["No.",499,501],
  ["Or?  Okay, I mean, I'll do my best to take care of you but again, I'm only so good and I am not going to pretend.",501,508],
  ["Let me think on that.",508,509],
  ["Okay.",509,510],
  ["I'll think on that now.",510,512],
  ["I think, I think it will be good at least to sit down and say, ""Do you have a better solution than what I'm proposing"" and if he does and it sounds good to you, then I will take it over from a prescribing point of view so you don't need _____.",512,523],
  ["They give shots, right?",523,524],
  ["He can give shots.  So, I can even do those.  So, what if the shot helped?",524,530],
  ["No.  My fear is I don't trust them when I have to, can't give me the shot to take _____.",530,535],
  ["Which we can always do that but -",535,538],
  ["But why would I want to have some doctors do it _____ .",538,541],
  ["No.  Peterson is here all the time.",541,543],
  ["Oh!  I don't agree.",543,545],
  ["Yeah.  No, no.  He is a local.  So, you could have at least sit down in a brain-to-brain.",545,550],
  ["Um-hum.",550,551],
  ["You could see options and if he says, ""Well, it would be better if you did this, and then this combination of other pill types"" -",551,558],
  ["Yeah.",558,560],
  ["And then, if you thought, ""Yeah, works good"", and then, I could take it over.",560,564],
  ["Um-hum.",564,565],
  ["Ah, just an option, I mean -",565,566],
  ["Okay.",566,567],
  ["Because I want you to get out and do stuff and -",567,571],
  ["I'm trying.",571,572],
  ["- if there's somebody who can help you and do that better than I can, then, I'd say, go for it.  So, think about it in the back of your mind because there's other pain clinic in Woodstock as well that we had talked about.  Um, so, let say Peterson??  At least for a consultation as we call it.",572,589],
  ["I don't wanna make appointment with him _____, so that is canceled too.",589,593],
  ["I know it.  Well, when you're ready - So, any other questions or things we need to think about for today?",593,599],
  ["No, I don't have any.",599,601],
  ["Okay.  Do you need refills on any meds?",601,603],
  ["Not right now.",603,605],
  ["Okay.  Well, let me know if you do.",605,607],
  ["I probably got long enough for another month.",607,609],
  ["Okay.",609,610],
  ["I'll call you.",610,611],
  ["Okay.  And then, let me know, if you wouldn't mind, if your blood pressure is high at home, then please give me a call.",611,615],
  ["Okay.  I will.",615,617],
  ["And just give me a heads-up.",617,618],
  ["um.",618,620],
  ["So, the big thing I'd like to get done before now and the next time we get together would be drawing the labs.",620,624],
  ["Okay.",624,626],
  ["So, those you should do fasting like you've done before but you can drink lots of water.",626,630],
  ["Okay.  That's for, what, 12 hours?",630,633],
  ["Yeah.  That would be perfect.  all right.  Remember this we have lungs?",633,637],
  ["Yeah.",637,638],
  ["Heart sounds good.  Let me have you - when you're ready, a big deep breath in and out of your mouth.",638,644],
  ["[Breathing in]",644,646],
  ["Yes.",646,647],
  ["[Breathing out]",647,648],
  ["Yes.",648,649]
]
