#!/bin/bash

# https://docs.docker.com/config/containers/multi-service_container/

rails s -b 0.0.0.0
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start my_first_process: $status"
  exit $status
fi

while sleep 60; do
done
