ARG image=orals-dev
FROM $image
ARG rails_env=development
ENV RAILS_ENV=$rails_env
RUN service cron start
RUN bundle exec whenever --set environment=development
RUN bundle exec whenever --set output='/app/log/whenever.log'
RUN bundle exec whenever --update-crontab
CMD rails s -b 0.0.0.0
EXPOSE 3000
