FROM ruby:2.6.3-slim-buster
RUN apt update -qq \
  && apt install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    postgresql-client \
    nodejs \
    ffmpeg \
    cron \
    nano
COPY Gemfile* /tmp/
WORKDIR /tmp
RUN bundle install
RUN bundle exec wheneverize .
RUN apt remove -y --purge build-essential \
  && apt clean autoclean \
  && apt autoremove -y \
  && rm -rf \
    /var/lib/apt \
    /var/lib/dpkg \
    /var/lib/cache \
    /var/lib/log
ARG rails_env=development
ENV RAILS_ENV=$rails_env
RUN mkdir /app
WORKDIR /app
COPY . /app
RUN rm -f ./tmp/pids/server.pid
RUN if [ "$RAILS_ENV" != "development" ]; then bundle exec rake assets:precompile --trace ; fi

