FROM ruby:2.7.0-buster
RUN apt update -qq \
  && apt install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    postgresql-client \
    nodejs \
    ffmpeg \
    vim
COPY Gemfile* /tmp/
WORKDIR /tmp
ARG rails_env=development
ENV RAILS_ENV=$rails_env
WORKDIR /app
COPY . /app
RUN gem install bundler
RUN bundle install
RUN bundle exec wheneverize .
RUN bundle exec whenever -s 'environment=$RAILS_ENV'
RUN mkdir /app
RUN rm -f ./tmp/pids/server.pid
RUN if [ "$RAILS_ENV" != "development" ]; then bundle exec rake assets:precompile --trace ; fi

RUN apt remove -y --purge build-essential \
  && apt clean autoclean \
  && apt autoremove -y \
  && rm -rf \
    /var/lib/apt \
    /var/lib/dpkg \
    /var/lib/cache \
    /var/lib/log
