FROM ruby:2.6.3-slim-buster
RUN apt update -qq \
  && apt install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    postgresql-client \
    nodejs \
    exim4 \
    ffmpeg
COPY Gemfile* /tmp/
WORKDIR /tmp
RUN bundle install
RUN apt remove -y --purge build-essential \
  && apt clean autoclean \
  && apt autoremove -y \
  && rm -rf \
    /var/lib/apt \
    /var/lib/dpkg \
    /var/lib/cache \
    /var/lib/log
RUN mkdir /app
WORKDIR /app
COPY . /app
RUN rm -f ./tmp/pids/server.pid
RUN bundle exec rake assets:precompile --trace
