source 'https://rubygems.org'
git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end
gem 'rails', '6.0.0.rc1'
gem 'concurrent-ruby'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'haml'
gem 'devise', '>= 4.7.1'
gem 'devise_invitable', '~> 1.7.0'
gem 'awesome_print'
gem 'rspec-rails'
gem 'sassc-rails', '>= 2.0.0'
gem 'font-awesome-rails'
gem 'tether-rails'
gem 'attr_encrypted'
gem 'coffee-rails', '~> 5.0.0'
gem 'nokogiri', '>= 1.10.8'
gem 'loofah', '>= 2.3.1'
gem 'rails-html-sanitizer', '>= 1.0.4'
gem 'sprockets', '>= 3.7.2'
gem 'ffi', '>= 1.9.24'
gem 'rack', '>= 2.0.6'
gem 'mini_racer'
gem 'inline_svg'
gem 'twilio-ruby', '~> 5.21.1'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'jbuilder', '~> 2.9'
gem 'pg', '~> 0.18'
gem 'puma', '>= 3.12.5'
gem 'geocoder', '>= 1.6.1'
gem 'uglifier', '>= 1.3.0'
gem 'aws-sdk-rails'
gem 'aws-sdk-s3'
gem 'aws-sdk-transcribeservice'
gem 'aws-sdk-comprehendmedical'
gem 'daemons'
gem 'delayed_job_active_record'
gem 'ahoy_matey'
gem 'selenium-webdriver'
gem 'rspec'
gem 'browserstack-local'
gem 'aws-ses', '~> 0.6.0', require: 'aws/ses'
gem 'websocket-extensions', '>= 0.1.5'
group :development do
  gem 'interactive_editor'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'letter_opener'
  gem 'byebug', platform: :mri
  gem 'gem-licenses'
end
