branch-defaults:
  multi-container:
    environment: orals-staging
global:
  application_name: orals
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Multi-container Docker 18.06.1-ce (Generic)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
