amazon:
  service: S3
  access_key_id: <%= Orals::Application.credentials.aws[:access_key_id] %> 
  secret_access_key: <%= Orals::Application.credentials.aws[:secret_access_key] %> 
  region: <%= Orals::Application.credentials.aws[:region] %>
  bucket: <%= Orals::Application.credentials[Rails.env.to_sym][:active_storage_bucket_name] %>
