amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws[:access_key_id] %> 
  secret_access_key: <%= Rails.application.credentials.aws[:secret_access_key] %> 
  region: <%= Rails.application.credentials.aws[:region] %>
  bucket: <%= Rails.application.credentials[Rails.env.to_sym][:media_bucket_name] %>
